### Occupant satisfaction

```{r}
#| echo: false
#| fig-width: 10
#| fig-height: 1.25
#| fig-align: center
#| fig-dpi: 500

satisfaction_levels <- c("-3", "-2", "-1", "0", "+1", "+2", "+3")
satisfaction_labels <- c("Very\nDissatisfied", "Dissatisfied", "Somewhat\nDissatisfied", "Neither",  "Somewhat\nSatisfied", "Satisfied", "Very\nSatisfied")
satisfaction_cols <- c("#ba3b50", "#cf6b61", "#d09da9", '#f3e8e7', "#c2e8bb", "#8bcc8a", "#4cb15e")

df <- data.frame(
  level = factor(satisfaction_levels, levels = satisfaction_levels),
  label = satisfaction_labels,
  color = satisfaction_cols,
  x = seq_along(satisfaction_levels),
  y = 1
)

library(ggplot2)

df$text <- paste0(df$level, "\n", df$label, "\n", df$color)

ggplot(df, aes(x = x, y = y)) +
  geom_tile(aes(fill = color), height = 0.8) +
  geom_text(
    aes(label = level),
    y = 1.7,
    size = 3
  ) +
  geom_text(
    aes(label = color),
    y = 1,
    size = 3,
    family = "mono",
    color = "black"
  ) +
  geom_text(
    aes(label = label),
    y = 0.2,
    size = 3,
  ) +
  scale_fill_identity() +
  coord_cartesian(ylim = c(0.2, 1.8), clip = "off") +
  theme_void() +
  theme(
    plot.margin = margin(10, 5, 10, 5)
  )

```

```{r}
#| code-fold: true

satisfaction_levels <- c("-3", "-2", "-1", "0", "+1", "+2", "+3")
satisfaction_labels <- c("Very\nDissatisfied", "Dissatisfied", "Somewhat\nDissatisfied", "Neither",  "Somewhat\nSatisfied", "Satisfied", "Very\nSatisfied")
satisfaction_cols <- c("#ba3b50", "#cf6b61", "#d09da9", '#f3e8e7', "#c2e8bb", "#8bcc8a", "#4cb15e")

```
---


### Thermal sensation

```{r}
#| echo: false
#| fig-width: 10
#| fig-height: 1.25
#| fig-align: center
#| fig-dpi: 500

thermal_sensation_levels <- c("-3", "-2", "-1", "0", "+1", "+2", "+3")
thermal_sensation_labels <- c("Cold", "Cool", "Slightly cool", "Neutral", "Slightly warm", "Warm", "Hot")
thermal_sensation_cols <- c("#6b8dd6", "#82c6ed","#b8e4f7","#c9e0b0","#f7a9b7","#eb6b58","#b44a4a")

df <- data.frame(
  level = factor(thermal_sensation_levels, levels = thermal_sensation_levels),
  label = thermal_sensation_labels,
  color = thermal_sensation_cols,
  x = seq_along(thermal_sensation_levels),
  y = 1
)

library(ggplot2)

df$text <- paste0(df$level, "\n", df$label, "\n", df$color)

ggplot(df, aes(x = x, y = y)) +
  geom_tile(aes(fill = color), height = 0.8) +
  geom_text(
    aes(label = level),
    y = 1.7,
    size = 3
  ) +
  geom_text(
    aes(label = color),
    y = 1,
    size = 3,
    family = "mono",
    color = "black"
  ) +
  geom_text(
    aes(label = label),
    y = 0.2,
    size = 3,
  ) +
  scale_fill_identity() +
  coord_cartesian(ylim = c(0.2, 1.8), clip = "off") +
  theme_void() +
  theme(
    plot.margin = margin(10, 5, 10, 5)
  )

```

```{r}
#| code-fold: true

thermal_sensation_levels <- c("-3", "-2", "-1", "0", "+1", "+2", "+3")
thermal_sensation_labels <- c("Cold", "Cool", "Slightly cool", "Neutral", "Slightly warm", "Warm", "Hot")
thermal_sensation_palette <- c("#6b8dd6","#82c6ed","#b8e4f7","#c9e0b0","#f7a9b7","#eb6b58","#b44a4a")

```
---

### Thermal preference

```{r}
#| echo: false
#| fig-width: 10
#| fig-height: 1.25
#| fig-align: center
#| fig-dpi: 500

thermal_preference_levels <- c("-1", "0", "+1")
thermal_preference_labels <- c("Cooler", "No change", "Warmer")
thermal_preference_cols <- c("#82c6ed","#c9e0b0","#eb6b58")

df <- data.frame(
  level = factor(thermal_preference_levels, levels = thermal_preference_levels),
  label = thermal_preference_labels,
  color = thermal_preference_cols,
  x = seq_along(thermal_preference_levels),
  y = 1
)

library(ggplot2)

df$text <- paste0(df$level, "\n", df$label, "\n", df$color)

ggplot(df, aes(x = x, y = y)) +
  geom_tile(aes(fill = color), height = 0.8) +
  geom_text(
    aes(label = level),
    y = 1.7,
    size = 3
  ) +
  geom_text(
    aes(label = color),
    y = 1,
    size = 3,
    family = "mono",
    color = "black"
  ) +
  geom_text(
    aes(label = label),
    y = 0.2,
    size = 3,
  ) +
  scale_fill_identity() +
  coord_cartesian(ylim = c(0.2, 1.8), clip = "off") +
  theme_void() +
  theme(
    plot.margin = margin(10, 5, 10, 5)
  )

```

```{r}
#| code-fold: true

thermal_preference_levels <- c("-1", "0", "+1")
thermal_preference_labels <- c("Cooler", "No change", "Warmer")
thermal_preference_cols <- c("#82c6ed","#c9e0b0","#eb6b58")

```